query Search(
	$query: String!
	$usersLimit: Int
	$usersOffset: Int
	$postsLimit: Int
	$postsOffset: Int
	$hashtagsLimit: Int
	$hashtagsOffset: Int
) {
	search(
		query: $query
		usersLimit: $usersLimit
		usersOffset: $usersOffset
		postsLimit: $postsLimit
		postsOffset: $postsOffset
		hashtagsLimit: $hashtagsLimit
		hashtagsOffset: $hashtagsOffset
	) {
		users {
			id
			userName
			firstName
			lastName
			picture
			followerCount
			posts {
				id
				thumbnailUrl
				messageCount
				likeCount
				imageStatus
				imageKey
			}
		}
		posts {
			id
			author {
				id
				firstName
				lastName
				picture
				userName
			}
			messageCount
			likeCount
			isLikedByCurrentUser
			description
			thumbnailUrl
			createdAt
			imageStatus
			imageKey
		}
		hashtags {
			id
			name
			postCount
		}
	}
}
