scalar Upload

type Post {
  id: Int!
  description: String!
  imageUrl: String!
  authorId: Int!
  author: UserUgram!
  createdAt: DateTime!
  hashtags: [Hashtag!]
  mentionedUsers:[UserUgram!]
}

extend type Query {
  post(id: Int!): Post
  posts(limit: Int, offset: Int): [Post!]!
  postsByAuthor(authorId: Int!, limit: Int, offset: Int): [Post!]!
}

input CreatePostInput {
  description: String!
  image: Upload!
  authorId: Int!
  hashtags: [String!]
  mentionedUsers: [Int!]
}

extend type Mutation {
  createPost(data: CreatePostInput!): Post!
}

