scalar Upload

type Post {
	id: Int!
	description: String!
	imageUrl: String
	thumbnailUrl: String
	authorId: Int!
	imageKey: String!
	imageStatus: String!
	author: UserUgram!
	createdAt: DateTime!
	hashtags: [Hashtag!]
	mentionedUsers: [UserUgram!]	
	messageCount: Int!
	likeCount: Int!
	isLikedByCurrentUser: Boolean!
}

extend type Query {
	post(id: Int!): Post
	posts(limit: Int, offset: Int): [Post!]!
	postsByAuthor(authorId: Int!, limit: Int, offset: Int): [Post!]!
}

input CreatePostInput {
	description: String!
	image: Upload!
	authorId: Int!
	hashtags: [String!]
	mentionedUsers: [Int!]
}

extend type Mutation {
	createPost(data: CreatePostInput!): Post!
	deletePost(id: Int!): Post!
	updatePost(id: Int!, description: String!): Post!
}
