type UserUgram {
  id: Int!
  userName: String!
  email: String!
  firstName: String!
  lastName: String!
  phoneNumber: String!
  picture: String
  createdAt: String!
  posts: [Post!]
}

extend type Query {
  user(id: Int!): UserUgram
  users(limit: Int, offset: Int): [UserUgram!]!
}

extend type Mutation {
  createUser(
    userName: String!
    email: String!
    password: String!
    firstName: String!
    lastName: String!
    phoneNumber: String!
    picture: String
    createdAt: String!
  ): UserUgram!
  
  updateUser(
    id: Int!
    email: String
    firstName: String
    lastName: String
    phoneNumber: String
    picture: Upload
  ): UserUgram!
}
