export const mockPosts = [
	{
		id: "1",
		author: {
			username: "john_doe",
			avatarUrl: "https://i.pravatar.cc/150?img=1",
			avatarFallback: "JD",
		},
		imageUrl: "https://picsum.photos/seed/post1/1080/1080",
		aspectRatio: "square" as const,
		publishedAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
		description: "Beautiful sunset at the beach 🌅 @jane_smith #sunset #beach #photography",
		likes: 1243,
		comments: 42,
		isLiked: true,
	},
	{
		id: "2",
		author: {
			username: "jane_smith",
			avatarUrl: "https://i.pravatar.cc/150?img=5",
			avatarFallback: "JS",
		},
		imageUrl: "https://picsum.photos/seed/post2/1080/1350",
		aspectRatio: "portrait" as const,
		publishedAt: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
		description: "Morning coffee vibes ☕️ #coffee #morning #lifestyle",
		likes: 892,
		comments: 18,
		isLiked: false,
	},
	{
		id: "3",
		author: {
			username: "travel_explorer",
			avatarUrl: "https://i.pravatar.cc/150?img=8",
			avatarFallback: "TE",
		},
		imageUrl: "https://picsum.photos/seed/post3/1080/566",
		aspectRatio: "landscape" as const,
		publishedAt: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
		description:
			"Mountain views from the top 🏔️ Amazing hiking experience with @john_doe #travel #mountains #adventure #hiking",
		likes: 2156,
		comments: 87,
		isLiked: false,
	},
	{
		id: "4",
		author: {
			username: "foodie_lover",
			avatarUrl: "https://i.pravatar.cc/150?img=12",
			avatarFallback: "FL",
		},
		imageUrl: "https://picsum.photos/seed/post4/1080/1080",
		aspectRatio: "square" as const,
		publishedAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
		description: "Homemade pasta night 🍝 Recipe in bio! #food #cooking #pasta #italian",
		likes: 634,
		comments: 23,
		isLiked: true,
	},
	{
		id: "5",
		author: {
			username: "urban_photographer",
			avatarUrl: "https://i.pravatar.cc/150?img=15",
			avatarFallback: "UP",
		},
		imageUrl: "https://picsum.photos/seed/post5/1080/1350",
		aspectRatio: "portrait" as const,
		publishedAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
		description: "City lights and night vibes 🌃 #citylife #photography #urban #nightphotography",
		likes: 1789,
		comments: 56,
		isLiked: false,
	},
	{
		id: "6",
		author: {
			username: "john_doe",
			avatarUrl: "https://i.pravatar.cc/150?img=1",
			avatarFallback: "JD",
		},
		imageUrl: "https://picsum.photos/seed/post6/1080/1080",
		aspectRatio: "square" as const,
		publishedAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
		description: "New adventure begins! #travel #adventure",
		likes: 945,
		comments: 31,
		isLiked: false,
	},
	{
		id: "7",
		author: {
			username: "john_doe",
			avatarUrl: "https://i.pravatar.cc/150?img=1",
			avatarFallback: "JD",
		},
		imageUrl: "https://picsum.photos/seed/post7/1080/1080",
		aspectRatio: "square" as const,
		publishedAt: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
		description: "Good vibes only ✨ #lifestyle #mood",
		likes: 1567,
		comments: 45,
		isLiked: true,
	},
	{
		id: "8",
		author: {
			username: "john_doe",
			avatarUrl: "https://i.pravatar.cc/150?img=1",
			avatarFallback: "JD",
		},
		imageUrl: "https://picsum.photos/seed/post8/1080/1080",
		aspectRatio: "square" as const,
		publishedAt: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString(),
		description: "Throwback to summer days 🌞 #summer #memories",
		likes: 2043,
		comments: 67,
		isLiked: false,
	},
];

export const mockUserProfile = {
	username: "john_doe",
	firstName: "John",
	lastName: "Doe",
	email: "john.doe@example.com",
	phoneNumber: "+1 (555) 123-4567",
	bio: "Photography enthusiast 📸 | Travel lover 🌍 | Coffee addict ☕️",
	avatarUrl: "https://i.pravatar.cc/150?img=1",
	avatarFallback: "JD",
	joinedDate: "2024-01-15T00:00:00.000Z",
	postsCount: 48,
	followersCount: 1234,
	followingCount: 567,
};
